// include/devices/icamera.h
#pragma once

#include "devices/device_types.h"
#include <string>
#include <vector>
#include <cstdint>
#include <functional>

namespace devices {

// Capture complete event data
struct CaptureCompleteEvent {
    std::string captureId;
    std::vector<uint8_t> imageData;  // JPEG or PNG binary
    std::string imageFormat;         // "jpeg", "png", etc.
    uint32_t width;
    uint32_t height;
    bool success;
    std::string errorMessage;  // On failure
    DeviceState state;
};

// Camera settings
struct CameraSettings {
    uint32_t resolutionWidth;
    uint32_t resolutionHeight;
    std::string imageFormat;  // "jpeg", "png"
    uint32_t quality;         // JPEG quality (1-100)
    bool autoFocus;
};

// Camera interface (for future implementation)
class ICamera {
public:
    virtual ~ICamera() = default;

    // Get device information
    virtual DeviceInfo getDeviceInfo() const = 0;

    // Capture photo (async)
    // captureId is generated by client and passed
    virtual bool capture(const std::string& captureId) = 0;

    // Check state
    virtual DeviceState getState() const = 0;

    // Start preview
    virtual bool startPreview() = 0;

    // Stop preview
    virtual bool stopPreview() = 0;

    // Change settings
    virtual bool setSettings(const CameraSettings& settings) = 0;

    // Get current settings
    virtual CameraSettings getSettings() const = 0;

    // Set event callbacks
    virtual void setCaptureCompleteCallback(std::function<void(const CaptureCompleteEvent&)> callback) = 0;
    virtual void setStateChangedCallback(std::function<void(DeviceState)> callback) = 0;
};

} // namespace devices
