// include/devices/iprinter.h
#pragma once

#include "devices/device_types.h"
#include <string>
#include <vector>
#include <cstdint>
#include <functional>

namespace devices {

// Print job complete event data
struct PrintJobCompleteEvent {
    std::string jobId;
    bool success;
    std::string errorMessage;  // On failure
    DeviceState state;
};

// Printer capabilities information
struct PrinterCapabilities {
    bool supportsColor;
    bool supportsDuplex;
    std::vector<std::string> supportedPaperSizes;
    uint32_t maxResolutionDpi;
};

// Printer interface (for future implementation)
class IPrinter {
public:
    virtual ~IPrinter() = default;

    // Get device information
    virtual DeviceInfo getDeviceInfo() const = 0;

    // Print request (async)
    // jobId is generated by client and passed
    virtual bool print(const std::string& jobId, const std::vector<uint8_t>& printData) = 0;

    // Print from file path (avoids loading into memory; preferred when client sends filePath).
    // orientation: "portrait" (세로) or "landscape" (가로). Layout 선택에 따라 클라이언트가 전달.
    // Default returns false; adapters that support it (e.g. GDI FromFile) override.
    virtual bool printFromFile(const std::string& jobId, const std::string& filePath, const std::string& orientation = "portrait") { (void)jobId; (void)filePath; (void)orientation; return false; }

    // Check state
    virtual DeviceState getState() const = 0;

    // Reset printer
    virtual bool reset() = 0;

    // Get capabilities
    virtual PrinterCapabilities getCapabilities() const = 0;

    // Set event callbacks
    virtual void setPrintJobCompleteCallback(std::function<void(const PrintJobCompleteEvent&)> callback) = 0;
    virtual void setStateChangedCallback(std::function<void(DeviceState)> callback) = 0;
};

} // namespace devices
